name: my-model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: CML
        uses: iterative/setup-cml@v1
      - name: Main
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install tensorflow matplotlib pandas numpy torch keras sklearn
          python3 train.py 100
          python3 evaluation.py
          
          cat metrics.txt >> report.md
          cml-publish metrics.jpg --md >> report.md
          cml-send-comment report.md
          cml-send-github-check report.md
        shell: bash
